### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by sameeul** [DraconPern/fmjpeg2koj#14]
Hi, I have created a recipe for a `conda` package of `fmjpeg2koj`. Do you plan to create a Github tag so that we can refer to that tag to build the package?

Here is the recipe PR (https://github.com/conda-forge/staged-recipes/pull/22639)

**Comment by DraconPern** [comment]
Like a version tag?  Will 'v1.0.3' work for the current master?

**Comment by sameeul** [comment]
Yes, that should work.

**Comment by sameeul** [comment]
Thanks for creating the tag. I have updated my conda PR with the new tag. Hopefully this will get into the conda-forge package list within a week or two.
