### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by boxerab** [DraconPern/fmjpeg2koj#5]
I tried to do this a few years ago, but it was pretty messy.
What steps do I need to take to get an openjpeg-enabled build of DCMTK ?
Just put this folder with the other codecs ?

Also, how did you test encode/decode ?

**Comment by DraconPern** [comment]
Build DCMTK. Then build this.  Register this codec just like other built-in code.  Then link both to your program.  I have access to a lot of dicom images and other implementation of jp2k to test against.

**Comment by boxerab** [comment]
Thanks. May I ask what project you are using this for? I am a contributor to OpenJPEG, and also
am developing my own J2K codec.

**Comment by DraconPern** [comment]
It's being used in production in https://github.com/DraconPern/dovo  I am not sure if other projects are using it..

**Comment by boxerab** [comment]
Cool. Thanks.
