### ISSUE TITLE
The build fails over linux.

### ISSUE THREAD

**Issue by informumar** [DraconPern/fmjpeg2koj#7]
Linker fails to link against the references in openjpeg libraries. If line 16,17,18 are commented out in CMakelists.txt then the build succeeds. Submitting the error and the CMakelists.txt.

Error:
$ ninja
[1/6] Linking CXX shared library libfmjpeg2k.so.1.0.2
FAILED: : && /usr/bin/c++  -fPIC    -shared -Wl,-soname,libfmjpeg2k.so.1 -o libfmjpeg2k.so.1.0.2 CMakeFiles/fmjpeg2k.dir/djcodecd.o CMakeFiles/fmjpeg2k.dir/djcodece.o CMakeFiles/fmjpeg2k.dir/djcparam.o CMakeFiles/fmjpeg2k.dir/djdecode.o CMakeFiles/fmjpeg2k.dir/djencode.o CMakeFiles/fmjpeg2k.dir/djrparam.o CMakeFiles/fmjpeg2k.dir/djutils.o CMakeFiles/fmjpeg2k.dir/memory_file.o -L/home/umar/.local/lib /usr/lib/libi2d.so.3.6.1.abi2 /usr/lib/libdcmjpeg.so.3.6.1.abi2 /usr/lib/libijg8.so.3.6.1.abi2 /usr/lib/libijg12.so.3.6.1.abi2 /usr/lib/libijg16.so.3.6.1.abi2 /usr/lib/libdcmjpls.so.3.6.1.abi2 /usr/lib/libcmr.so.3.6.1.abi2 /usr/lib/libdcmwlm.so.3.6.1.abi2 /usr/lib/libdcmpstat.so.3.6.1.abi2 /usr/lib/libdcmrt.so.3.6.1.abi2 /usr/lib/libdcmseg.so.3.6.1.abi2 /home/umar/.local/lib/libopenjp2.so.2.3.0 -lCharLS /usr/lib/libdcmtls.so.3.6.1.abi2 /usr/lib/libdcmsr.so.3.6.1.abi2 /usr/lib/libdcmimage.so.3.6.1.abi2 -ltiff -ljpeg -lpng -lxml2 /usr/lib/libdcmdsig.so.3.6.1.abi2 -lssl -lcrypto /usr/lib/libdcmqrdb.so.3.6.1.abi2 /usr/lib/libdcmnet.so.3.6.1.abi2 -lwrap /usr/lib/libdcmimgle.so.3.6.1.abi2 /usr/lib/libdcmfg.so.3.6.1.abi2 /usr/lib/libdcmiod.so.3.6.1.abi2 /usr/lib/libdcmdata.so.3.6.1.abi2 /usr/lib/liboflog.so.3.6.1.abi2 /usr/lib/libofstd.so.3.6.1.abi2 -lpthread -lz -lm -lpthread -Wl,-rpath,/home/umar/.local/lib: && :
CMakeFiles/fmjpeg2k.dir/djcodecd.o: In function `DJPEG2KDecoderBase::decodeFrame(DcmPixelSequence*, DJPEG2KCodecParameter const*, DcmItem*, unsigned int, unsigned int&, void*, unsigned int, int, unsigned short, unsigned short, unsigned short, unsigned short)':
djcodecd.cc:(.text+0x21a5): undefined reference to `opj_create_decompress'
djcodecd.cc:(.text+0x21ca): undefined reference to `opj_set_info_handler'
djcodecd.cc:(.text+0x21e8): undefined reference to `opj_set_warning_handler'
djcodecd.cc:(.text+0x2206): undefined reference to `opj_set_error_handler'
djcodecd.cc:(.text+0x2215): undefined reference to `opj_set_default_decoder_parameters'
djcodecd.cc:(.text+0x222e): undefined reference to `opj_setup_decoder'
djcodecd.cc:(.text+0x2246): undefined reference to `opj_stream_destroy'
djcodecd.cc:(.text+0x2260): undefined reference to `opj_destroy_codec'
djcodecd.cc:(.text+0x22df): undefined reference to `opj_read_header'
djcodecd.cc:(.text+0x2306): undefined reference to `opj_stream_destroy'
djcodecd.cc:(.text+0x2320): undefined reference to `opj_destroy_codec'
djcodecd.cc:(.text+0x233a): undefined reference to `opj_image_destroy'
djcodecd.cc:(.text+0x24fe): undefined reference to `opj_decode'
djcodecd.cc:(.text+0x251b): undefined reference to `opj_end_decompress'
djcodecd.cc:(.text+0x2542): undefined reference to `opj_stream_destroy'
djcodecd.cc:(.text+0x255c): undefined reference to `opj_destroy_codec'
djcodecd.cc:(.text+0x2576): undefined reference to `opj_image_destroy'
djcodecd.cc:(.text+0x274c): undefined reference to `opj_stream_destroy'
djcodecd.cc:(.text+0x2766): undefined reference to `opj_destroy_codec'
djcodecd.cc:(.text+0x2780): undefined reference to `opj_image_destroy'
CMakeFiles/fmjpeg2k.dir/djcodece.o: In function `DJPEG2KEncoderBase::compressRawFrame(unsigned char const*, unsigned short, unsigned short, unsigned short, unsigned short, unsigned short, bool, OFString const&, DcmPixelSequence*, OFList<unsigned int>&, unsigned long&, DJPEG2KCodecParameter const*) const':
djcodece.cc:(.text+0x3054): undefined reference to `opj_set_default_encoder_parameters'
djcodece.cc:(.text+0x3251): undefined reference to `opj_create_compress'
djcodece.cc:(.text+0x3276): undefined reference to `opj_set_info_handler'
djcodece.cc:(.text+0x3294): undefined reference to `opj_set_warning_handler'
djcodece.cc:(.text+0x32b2): undefined reference to `opj_set_error_handler'
djcodece.cc:(.text+0x32e5): undefined reference to `opj_setup_encoder'
djcodece.cc:(.text+0x3308): undefined reference to `opj_destroy_codec'
djcodece.cc:(.text+0x33ba): undefined reference to `opj_start_compress'
djcodece.cc:(.text+0x3430): undefined reference to `opj_encode'
djcodece.cc:(.text+0x34b1): undefined reference to `opj_end_compress'
djcodece.cc:(.text+0x3515): undefined reference to `opj_stream_destroy'
djcodece.cc:(.text+0x352f): undefined reference to `opj_destroy_codec'
djcodece.cc:(.text+0x3549): undefined reference to `opj_image_destroy'
CMakeFiles/fmjpeg2k.dir/djcodece.o: In function `DJPEG2KEncoderBase::compressRenderedFrame(DcmPixelSequence*, DicomImage*, OFString const&, OFList<unsigned int>&, unsigned long&, DJPEG2KCodecParameter const*, unsigned int, FMJPEG2KRepresentationParameter const*) const':
djcodece.cc:(.text+0x4f37): undefined reference to `opj_set_default_encoder_parameters'
djcodece.cc:(.text+0x5248): undefined reference to `opj_create_compress'
djcodece.cc:(.text+0x526d): undefined reference to `opj_set_info_handler'
djcodece.cc:(.text+0x528b): undefined reference to `opj_set_warning_handler'
djcodece.cc:(.text+0x52a9): undefined reference to `opj_set_error_handler'
djcodece.cc:(.text+0x52dc): undefined reference to `opj_setup_encoder'
djcodece.cc:(.text+0x52ff): undefined reference to `opj_destroy_codec'
djcodece.cc:(.text+0x53b9): undefined reference to `opj_start_compress'
djcodece.cc:(.text+0x543a): undefined reference to `opj_encode'
djcodece.cc:(.text+0x54bb): undefined reference to `opj_end_compress'
djcodece.cc:(.text+0x551f): undefined reference to `opj_stream_destroy'
djcodece.cc:(.text+0x552e): undefined reference to `opj_destroy_codec'
djcodece.cc:(.text+0x553d): undefined reference to `opj_image_destroy'
CMakeFiles/fmjpeg2k.dir/djcodece.o: In function `frametoimage(unsigned char const*, int, OFString, int, int, int, int, bool, opj_cparameters*, opj_image**)':
djcodece.cc:(.text+0x5a87): undefined reference to `opj_image_create'
CMakeFiles/fmjpeg2k.dir/memory_file.o: In function `opj_stream_create_memory_stream(DecodeData*, unsigned int, bool)':
memory_file.cpp:(.text+0x35a): undefined reference to `opj_stream_create'
memory_file.cpp:(.text+0x387): undefined reference to `opj_stream_set_user_data'
memory_file.cpp:(.text+0x39e): undefined reference to `opj_stream_set_user_data_length'
memory_file.cpp:(.text+0x3b4): undefined reference to `opj_stream_set_read_function'
memory_file.cpp:(.text+0x3ca): undefined reference to `opj_stream_set_write_function'
memory_file.cpp:(.text+0x3e0): undefined reference to `opj_stream_set_skip_function'
memory_file.cpp:(.text+0x3f6): undefined reference to `opj_stream_set_seek_function'
/usr/bin/ld: libfmjpeg2k.so.1.0.2: hidden symbol `opj_read_header' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[CMakeLists.txt](https://github.com/DraconPern/fmjpeg2koj/files/1739712/CMakeLists.txt)

**Comment by DraconPern** [comment]
Can you clarify why commenting out those three lines effects linking?

**Comment by DraconPern** [comment]
oh, you are trying to link to a shared openjpeg library.  Since no major linux distribution has openjpeg, the cmake does a static link.

**Comment by informumar** [comment]
Okay, Thank you very much!
